/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:40:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS public.glossaryid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS public.t_glossary CASCADE
;

/* Create Tables */

CREATE TABLE public.t_glossary
(
	term varchar(255) NULL,
	type varchar(255) NULL,
	meaning text NULL,
	glossaryid integer NOT NULL   DEFAULT NEXTVAL(('glossaryid_seq'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.t_glossary ADD CONSTRAINT pk_glossary
	PRIMARY KEY (glossaryid)
;

CREATE INDEX idx_glossary_term ON public.t_glossary (term ASC)
;

CREATE INDEX idx_glossary_type ON public.t_glossary (type ASC)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE public.glossaryid_seq INCREMENT 1 START 1
;