/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:40:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS public.t_taggedvalue CASCADE
;

/* Create Tables */

CREATE TABLE public.t_taggedvalue
(
	property_id varchar(40) NOT NULL,
	element_id varchar(40) NOT NULL,
	tagvalue text NOT NULL,
	notes text NULL,
	baseclass varchar(100) NULL,
	object_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.t_taggedvalue ADD CONSTRAINT "PK_t_taggedvalue"
	PRIMARY KEY (property_id)
;

CREATE INDEX "IXFK_t_taggedvalue_t_object" ON public.t_taggedvalue (object_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE public.t_taggedvalue ADD CONSTRAINT "FK_t_taggedvalue_t_object"
	FOREIGN KEY (object_id) REFERENCES public.t_object (object_id) ON DELETE No Action ON UPDATE No Action
;