/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:40:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS connector_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS t_connector CASCADE
;

/* Create Tables */

CREATE TABLE t_connector
(
	connector_id integer NOT NULL   DEFAULT NEXTVAL(('connector_id_seq'::text)::regclass),
	name varchar(255) NULL,
	direction varchar(50) NULL,
	notes text NULL,
	connector_type varchar(50) NULL,
	start_object_id integer NULL   DEFAULT 0,
	end_object_id integer NULL   DEFAULT 0,
	ims_guid varchar(40) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE t_connector ADD CONSTRAINT "PK_t_connector"
	PRIMARY KEY (connector_id)
;

ALTER TABLE t_connector 
  ADD CONSTRAINT uq_connector_ims_guid UNIQUE (ims_guid)
;

ALTER TABLE t_connector 
  ADD CONSTRAINT conn_unique UNIQUE (direction,start_object_id,end_object_id)
;

CREATE INDEX "IXFK_t_connector_t_object" ON t_connector (start_object_id ASC)
;

CREATE INDEX "IXFK_t_connector_t_object_02" ON t_connector (end_object_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE t_connector ADD CONSTRAINT "FK_t_connector_t_object"
	FOREIGN KEY (start_object_id) REFERENCES public.t_object (object_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE t_connector ADD CONSTRAINT "FK_t_connector_t_object_02"
	FOREIGN KEY (end_object_id) REFERENCES public.t_object (object_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE connector_id_seq INCREMENT 1 START 1
;