/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:40:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS package_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS t_package CASCADE
;

/* Create Tables */

CREATE TABLE t_package
(
	package_id integer NOT NULL   DEFAULT NEXTVAL(('package_id_seq'::text)::regclass),
	name varchar(255) NULL,
	parent_id integer NULL   DEFAULT 0,
	notes text NULL,
	ims_guid varchar(40) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE t_package ADD CONSTRAINT "PK_t_package"
	PRIMARY KEY (package_id)
;

ALTER TABLE t_package 
  ADD CONSTRAINT uq_packadge_ims_guid UNIQUE (ims_guid)
;

CREATE INDEX ix_package_name ON t_package (name ASC)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE package_id_seq INCREMENT 1 START 1
;