/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:42:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS order_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS t_order CASCADE
;

/* Create Tables */

CREATE TABLE t_order
(
	order_id integer NOT NULL   DEFAULT NEXTVAL(('order_id_seq'::text)::regclass),
	product_name varchar(50) NULL,
	product_count integer NULL   DEFAULT 0,
	product_cost double precision NULL,
	notes text NULL,
	user_id integer NULL   DEFAULT 0,
	date_create time without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE t_order ADD CONSTRAINT "PK_t_order"
	PRIMARY KEY (order_id)
;

CREATE INDEX "IXFK_t_order_t_User" ON t_order (user_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE t_order ADD CONSTRAINT "FK_t_order_t_User"
	FOREIGN KEY (user_id) REFERENCES "t_User" (user_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE order_id_seq INCREMENT 1 START 1
;