/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-���-2024 0:42:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS todo_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "t_TODO" CASCADE
;

/* Create Tables */

CREATE TABLE "t_TODO"
(
	todo_id integer NOT NULL   DEFAULT NEXTVAL(('todo_id_seq'::text)::regclass),
	notes text NULL,
	date_time timestamp without time zone NULL,
	status varchar(50) NULL,	-- 'планирование, отложен, в работе, выполнил'
	user_id integer NULL,
	datecreate timestamp without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "t_TODO" ADD CONSTRAINT "PK_t_TODO"
	PRIMARY KEY (todo_id)
;

CREATE INDEX "IXFK_t_TODO_T_User" ON "t_TODO" (user_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "t_TODO" ADD CONSTRAINT "FK_t_TODO_T_User"
	FOREIGN KEY (user_id) REFERENCES "t_User" (user_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "t_TODO".status
	IS 'планирование, отложен, в работе, выполнил'
;

CREATE SEQUENCE todo_id_seq INCREMENT 1 START 1
;