/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 27-фев-2024 0:42:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS user_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "t_User" CASCADE
;

/* Create Tables */

CREATE TABLE "t_User"
(
	user_id integer NOT NULL   DEFAULT NEXTVAL(('user_id_seq'::text)::regclass),
	user_name varchar(255) NULL,
	user_email varchar(50) NULL,
	user_tell varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "t_User" ADD CONSTRAINT "PK_t_User"
	PRIMARY KEY (user_id)
;

ALTER TABLE "t_User" 
  ADD CONSTRAINT user_unique UNIQUE (user_email,user_tell)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE user_id_seq INCREMENT 1 START 1
;